/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ingestion activity over time (GitHub-style contribution graph). */
        get: operations["activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current ingest status. */
        get: operations["ingest_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/post/{site}/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single post by site and ID. */
        get: operations["get_post"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the most recently ingested posts. */
        get: operations["recent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Semantic search over indexed images. */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/similar/{site}/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find visually similar images to a known post. */
        get: operations["search_similar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic search using multipart form-data, including direct image upload. */
        post: operations["search_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all indexed sites with metadata. */
        get: operations["sites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A single day's activity entry. */
        ActivityDayDto: {
            /**
             * Format: int64
             * @description Number of posts ingested on this day.
             */
            count: number;
            /** @description Date in ISO 8601 format (YYYY-MM-DD). */
            date: string;
            /**
             * Format: double
             * @description Normalized activity level in [0.0, 1.0].
             */
            intensity: number;
        };
        /** @description Activity response. */
        ActivityDto: {
            /** Format: double */
            average: number;
            days: components["schemas"]["ActivityDayDto"][];
            /** Format: int64 */
            peak: number;
            /** Format: int64 */
            total: number;
        };
        /** @description Query parameters for the `/api/activity` endpoint. */
        ActivityParams: {
            /**
             * Format: int64
             * @description Number of days to look back (default 90, max 365).
             * @example 90
             */
            days?: number | null;
            /**
             * @description Sites to restrict results to. Repeated param or comma-separated.
             * @example [
             *       "rule34",
             *       "e621"
             *     ]
             */
            site?: string[];
        };
        /**
         * @description Standard API response envelope.
         *
         *     All successful responses are wrapped in this structure to provide
         *     consistent pagination metadata and a uniform client interface.
         */
        ApiResponse_ActivityDto: {
            /** @description Activity response. */
            data: {
                /** Format: double */
                average: number;
                days: components["schemas"]["ActivityDayDto"][];
                /** Format: int64 */
                peak: number;
                /** Format: int64 */
                total: number;
            };
            meta?: null | components["schemas"]["ResponseMeta"];
        };
        /**
         * @description Standard API response envelope.
         *
         *     All successful responses are wrapped in this structure to provide
         *     consistent pagination metadata and a uniform client interface.
         */
        ApiResponse_ErrorDto: {
            /** @description Error response body. */
            data: {
                error: string;
            };
            meta?: null | components["schemas"]["ResponseMeta"];
        };
        /**
         * @description Standard API response envelope.
         *
         *     All successful responses are wrapped in this structure to provide
         *     consistent pagination metadata and a uniform client interface.
         */
        ApiResponse_IngestStatusDto: {
            /** @description Snapshot of the ingest service status. */
            data: {
                active_sites: string[];
                is_running: boolean;
                last_checkpoint?: unknown;
            };
            meta?: null | components["schemas"]["ResponseMeta"];
        };
        /**
         * @description Standard API response envelope.
         *
         *     All successful responses are wrapped in this structure to provide
         *     consistent pagination metadata and a uniform client interface.
         */
        ApiResponse_PostDto: {
            /**
             * @description A post with full metadata.
             *
             *     Used across all endpoints that return post data (search, recent,
             *     similar, single post). The `score` field is only populated for search
             *     and similarity results.
             */
            data: {
                /** @description URL to the full-resolution image (falls back to thumbnail if unavailable). */
                direct_image_url: string;
                /**
                 * Format: int32
                 * @description Image height in pixels (0 if unknown).
                 */
                height: number;
                /**
                 * Format: int64
                 * @description Unix timestamp of when the post was ingested.
                 */
                ingestion_date: number;
                /**
                 * Format: int64
                 * @description Site-local post ID.
                 */
                post_id: number;
                /** @description Canonical URL to the post page on the source site. */
                post_url: string;
                /** @description Content rating (e.g. `"s"`, `"q"`, `"e"`). */
                rating?: string | null;
                /**
                 * Format: float
                 * @description Cosine similarity score in [0.0, 1.0]; only set for search/similar results.
                 */
                score?: number | null;
                /** @description Site name this post belongs to (e.g. `"rule34"`, `"e621"`). */
                site: string;
                /** @description Space-separated tags describing the image content. */
                tags?: string | null;
                /** @description URL to a small thumbnail image. */
                thumbnail_url: string;
                /**
                 * Format: int32
                 * @description Image width in pixels (0 if unknown).
                 */
                width: number;
            };
            meta?: null | components["schemas"]["ResponseMeta"];
        };
        /**
         * @description Standard API response envelope.
         *
         *     All successful responses are wrapped in this structure to provide
         *     consistent pagination metadata and a uniform client interface.
         */
        ApiResponse_Vec_PostDto: {
            data: {
                /** @description URL to the full-resolution image (falls back to thumbnail if unavailable). */
                direct_image_url: string;
                /**
                 * Format: int32
                 * @description Image height in pixels (0 if unknown).
                 */
                height: number;
                /**
                 * Format: int64
                 * @description Unix timestamp of when the post was ingested.
                 */
                ingestion_date: number;
                /**
                 * Format: int64
                 * @description Site-local post ID.
                 */
                post_id: number;
                /** @description Canonical URL to the post page on the source site. */
                post_url: string;
                /** @description Content rating (e.g. `"s"`, `"q"`, `"e"`). */
                rating?: string | null;
                /**
                 * Format: float
                 * @description Cosine similarity score in [0.0, 1.0]; only set for search/similar results.
                 */
                score?: number | null;
                /** @description Site name this post belongs to (e.g. `"rule34"`, `"e621"`). */
                site: string;
                /** @description Space-separated tags describing the image content. */
                tags?: string | null;
                /** @description URL to a small thumbnail image. */
                thumbnail_url: string;
                /**
                 * Format: int32
                 * @description Image width in pixels (0 if unknown).
                 */
                width: number;
            }[];
            meta?: null | components["schemas"]["ResponseMeta"];
        };
        /**
         * @description Standard API response envelope.
         *
         *     All successful responses are wrapped in this structure to provide
         *     consistent pagination metadata and a uniform client interface.
         */
        ApiResponse_Vec_SiteDto: {
            data: {
                /** Format: int64 */
                count: number;
                /** Format: int64 */
                earliest_ingestion: number;
                /** Format: int64 */
                latest_ingestion: number;
                name: string;
                /** Format: int64 */
                namespace: number;
            }[];
            meta?: null | components["schemas"]["ResponseMeta"];
        };
        /** @description Error response body. */
        ErrorDto: {
            error: string;
        };
        /** @description Snapshot of the ingest service status. */
        IngestStatusDto: {
            active_sites: string[];
            is_running: boolean;
            last_checkpoint?: unknown;
        };
        /**
         * @description A post with full metadata.
         *
         *     Used across all endpoints that return post data (search, recent,
         *     similar, single post). The `score` field is only populated for search
         *     and similarity results.
         */
        PostDto: {
            /** @description URL to the full-resolution image (falls back to thumbnail if unavailable). */
            direct_image_url: string;
            /**
             * Format: int32
             * @description Image height in pixels (0 if unknown).
             */
            height: number;
            /**
             * Format: int64
             * @description Unix timestamp of when the post was ingested.
             */
            ingestion_date: number;
            /**
             * Format: int64
             * @description Site-local post ID.
             */
            post_id: number;
            /** @description Canonical URL to the post page on the source site. */
            post_url: string;
            /** @description Content rating (e.g. `"s"`, `"q"`, `"e"`). */
            rating?: string | null;
            /**
             * Format: float
             * @description Cosine similarity score in [0.0, 1.0]; only set for search/similar results.
             */
            score?: number | null;
            /** @description Site name this post belongs to (e.g. `"rule34"`, `"e621"`). */
            site: string;
            /** @description Space-separated tags describing the image content. */
            tags?: string | null;
            /** @description URL to a small thumbnail image. */
            thumbnail_url: string;
            /**
             * Format: int32
             * @description Image width in pixels (0 if unknown).
             */
            width: number;
        };
        /** @description Query parameters for the `/api/recent` endpoint. */
        RecentParams: {
            /**
             * Format: int64
             * @description Number of results to return (default 20, max 100).
             * @example 20
             */
            limit?: number | null;
            /**
             * Format: int64
             * @description Pagination offset (default: 0).
             * @example 0
             */
            offset?: number | null;
            /**
             * @description Sites to restrict results to. Repeated param or comma-separated.
             * @example [
             *       "rule34",
             *       "e621"
             *     ]
             */
            site?: string[];
        };
        /** @description Pagination and query metadata. */
        ResponseMeta: {
            /** @description Number of items returned in this response. */
            count: number;
            /**
             * Format: int64
             * @description Offset for the next page (None if no more results).
             */
            next_offset?: number | null;
        };
        /** @description Query parameters for the `/api/search` endpoint. */
        SearchParams: {
            /**
             * @description Publicly accessible image URL to use as a visual query.
             * @example https://example.com/image.jpg
             */
            image_url?: string | null;
            /**
             * Format: float
             * @description Image weight for hybrid text+image queries, in [0.0, 1.0].
             * @example 0.5
             */
            image_weight?: number | null;
            /**
             * Format: int64
             * @description Maximum number of results to return (default: 10, max: 100).
             * @example 10
             */
            limit?: number | null;
            /**
             * @description Text query for semantic search.
             * @example fluffy cat sitting on a windowsill
             */
            q?: string | null;
            /**
             * @description Sites to restrict results to. Repeated param or comma-separated.
             *     Omit to search across all indexed sites.
             * @example [
             *       "rule34",
             *       "e621"
             *     ]
             */
            site?: string[];
        };
        /** @description Multipart form fields for `/api/search/upload`. */
        SearchUploadForm: {
            /**
             * Format: binary
             * @description Uploaded image file used as visual query.
             */
            image?: string | null;
            /**
             * Format: float
             * @description Image weight for hybrid text+image queries, in [0.0, 1.0].
             * @example 0.5
             */
            image_weight?: number | null;
            /**
             * Format: int64
             * @description Maximum number of results to return (default: 10, max: 100).
             * @example 10
             */
            limit?: number | null;
            /**
             * @description Text query for semantic search.
             * @example fluffy cat sitting on a windowsill
             */
            q?: string | null;
            /**
             * @description Sites to restrict results to. Comma-separated.
             * @example rule34,e621
             */
            site?: string | null;
        };
        /** @description Query parameters for the `/api/search/similar/{site}/{post_id}` endpoint. */
        SimilarParams: {
            /**
             * Format: int64
             * @description Maximum results to return (default 10, max 100).
             * @example 10
             */
            limit?: number | null;
        };
        /** @description Metadata about an indexed site. */
        SiteDto: {
            /** Format: int64 */
            count: number;
            /** Format: int64 */
            earliest_ingestion: number;
            /** Format: int64 */
            latest_ingestion: number;
            name: string;
            /** Format: int64 */
            namespace: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    activity: {
        parameters: {
            query?: {
                /** @description Days to look back (default 90, max 365) */
                days?: number;
                /** @description Sites to filter by (repeated or comma-separated) */
                site?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ActivityDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ErrorDto"];
                };
            };
        };
    };
    ingest_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingest status snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_IngestStatusDto"];
                };
            };
        };
    };
    get_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site name (e.g. rule34, e621) */
                site: string;
                /** @description Site-local post ID */
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Post found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PostDto"];
                };
            };
            /** @description Post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ErrorDto"];
                };
            };
        };
    };
    recent: {
        parameters: {
            query?: {
                /** @description Number of results (default 20, max 100) */
                limit?: number;
                /** @description Sites to filter by (repeated or comma-separated) */
                site?: string[];
                /** @description Pagination offset */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_PostDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ErrorDto"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                /** @description Text query for semantic search */
                q?: string;
                /** @description Publicly accessible image URL for visual search */
                image_url?: string;
                /** @description Sites to filter by (repeated or comma-separated) */
                site?: string[];
                /** @description Maximum results (default 10, max 100) */
                limit?: number;
                /** @description Image weight for hybrid queries [0.0-1.0] */
                image_weight?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_PostDto"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ErrorDto"];
                };
            };
        };
    };
    search_similar: {
        parameters: {
            query?: {
                /** @description Maximum results (default 10, max 100) */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Site name of the target post */
                site: string;
                /** @description Site-local post ID of the target */
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Similar posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_PostDto"];
                };
            };
            /** @description Target post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ErrorDto"];
                };
            };
        };
    };
    search_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Multipart form with optional q text, optional image file, optional comma-separated site, limit, and image_weight */
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["SearchUploadForm"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_PostDto"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ErrorDto"];
                };
            };
        };
    };
    sites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of indexed sites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_SiteDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ErrorDto"];
                };
            };
        };
    };
}
